### ISSUE TITLE
Diagnose Code Coverage Issues, and assign relevant work

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#101]
At the moment we're sitting at about [50%][1] code coverage.
For this sprint of our goals is to increase coverage, so in this issue I'll diagnose what is keeping our coverage down and assign the work needed to fix it.

  [1]: https://codecov.io/gh/TechnionYP5777/Bugquery "50%"

**Comment by AmitOhayon** [comment]
Current pitfalls (at least on serverside) are entities and dbparsing (which is going through a big makeover, so im not sure if now is the right time to deal with its coverage)

**Comment by ZivIzhar** [comment]
Since we're not testing the plugin yet, I won't address it.

Our problems in serverside are these:
1. entities - basically entities is a "structures" package. the reason it has such low coverage rate is because most of the untested lines are setters and getters. In my opinion it's OK not to test these classes since they are just unifying some data without any logic. I will make codecov ignore this package (as soon as I'll figure out how to :D )
2. dbparsing - as Amit wrote, it's going through a big makeover, however this makeover as far as I understand doesn't change this code's testability... which is a major issue. I am going to open an issue about discussing a database redesign...

Relevant work - 
1. entities - I'll figure out how to ignore these files in the codecov check.
2. dbparsing - I'll open an issue about redesign discussion

I'll close this issue after doing so.

**Comment by ZivIzhar** [comment]
apparently ignoring files using codecov with multiple projects in one maven project is problematic...
Im opening a new issue regarding this and closing this one.
