### ISSUE TITLE
dbparsing Redesign Discussion

### ISSUE THREAD

**Issue by ZivIzhar** [TechnionYP5777/Bugquery#102]
I think there should be a redesign in dbparsing.
To be clear, I'm not talking about the orm (dealt with in #76) - I'm reffering to our "database representation" in the code.

The problems in the current design as far as I can see **(if I'm wrong, please correct me)**:
* Testability - in the current design, there's A LOT of code that simply can not be tested.
* Scalability - Adding another source of data which is even slightly different from stackoverflow's will require a huge code changes in dbparsing while in an ideal design we can probably do it in 10~ lines.
* Usability - Doing things we didn't think we would need to do should be possible without too much effort. 

Let's discuss :) (no redesign is also an option)

**Comment by AmitOhayon** [comment]
@tonylekhtman convinced me that ORM is not right for us, mostly because it lacks optimizations which could be essential for us. We are rethinking the design of the entire DB department. Currently reading about [DAO pattern](https://www.tutorialspoint.com/design_pattern/data_access_object_pattern.htm).

**Comment by AmitOhayon** [comment]
after reading [this](http://stackoverflow.com/questions/41399679/is-it-good-idea-to-use-the-dao-design-patern-with-spring-boot-instead-of-using) I have changed my mind again. full documentation is [here](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/), we should read this before coming to conclusion

**Comment by AmitOhayon** [comment]
[Spring Test DBUnit](https://springtestdbunit.github.io/spring-test-dbunit/) could help too

**Comment by AmitOhayon** [comment]
last for today: we can configure an in-memory db profile for testing and use [this](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/integration-testing.html#__contextconfiguration) to use it on tests. more about embedded dbs [here](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html#jdbc-embedded-database-support)

**Comment by AmitOhayon** [comment]
testing db specifically in spring boot tutorial [here](https://blog.jayway.com/2014/07/04/integration-testing-a-spring-boot-application/) - saves configuration, probably suits us best

**Comment by AmitOhayon** [comment]
the most explicit example i found - [here](https://github.com/spring-projects/spring-data-examples/tree/master/jpa/example), but when trying to implement on our project it throws an exception. will try again tomorrow

**Comment by AmitOhayon** [comment]
regarding custom configuration for tests in a manner that runs tests on in-memory db vs. production on mysql server - it says [here](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-jpa-test) that:

> @DataJpaTest can be used if you want to test JPA applications. By default it will configure an in-memory embedded database, scan for @Entity classes and configure Spring Data JPA repositories. Regular @Component beans will not be loaded into the ApplicationContext.

so we can use this annotation to save context configuration time while running the tests and we don't need to define our own context.

**Comment by AmitOhayon** [comment]
[about embedded objects](https://en.wikibooks.org/wiki/Java_Persistence/Embeddables) (in our case stacktrace embedded in post)

**Comment by AmitOhayon** [comment]
Good news - we got over many obstacles regarding usage and testing of JPA and Spring Data, and got to the point where we created the table for posts like we wanted.
Apparently, creating the table for base class "post" also creates columns for each inheriting class (such as MinSOPost, StackOvrflowPost etc).
In order to complete the redesign issue, I need to know if there is any need to keep these inheriting classes - especially considering that we dropped many features regarding the site that could have used that extra information.
A compromise for now can be creating an extra column specifying the data's source, but we don't really need it at the moment because we know all of our posts come from stack overflow.
Please express your opinion ASAP so we can be done with it by sunday's meeting @ZivIzhar @yonilx @rodedzats @tonylekhtman

**Comment by yonzarecki** [comment]
Nah, I don't think we really need these classes. They were made with the future in mind, but if they are in the way there is no real reason to keep them IMO.

**Comment by AmitOhayon** [comment]
screenshots of the tables schemas (not all column types are correct, will be fixed soon)
![screenshot from 2017-05-12 13-01-20](https://cloud.githubusercontent.com/assets/1254412/25993681/7c6cb876-3713-11e7-8422-6c158cd94a1e.png)
![screenshot from 2017-05-12 13-02-20](https://cloud.githubusercontent.com/assets/1254412/25993682/7c8892c6-3713-11e7-8891-e2cdfc6cbb53.png)

**Comment by AmitOhayon** [comment]
Apparently to access an embedded object's property you need to name the method differently as explained [here](http://stackoverflow.com/questions/24441411/spring-data-jpa-find-by-embedded-object-property), so I'm hoping no one else will have to spend an hour on this issue 😢

**Comment by tonylekhtman** [comment]
@AmitOhayon and I finished.
With additional demands new issues would open in the future.
Closed.

**Comment by tonylekhtman** [comment]
@AmitOhayon and I finished.
With additional demands new issues would open in the future.
Closed.
