### ISSUE TITLE
No info abou RuntimeError exception

### ISSUE THREAD

**Issue by geniashand** [TechnionYP5777/Bugquery#185]
I'm running a simple program
![image](https://user-images.githubusercontent.com/23057153/27769144-35f026c6-5f2c-11e7-80f7-d5b95bf3dcef.png)
![image](https://user-images.githubusercontent.com/23057153/27769149-499eff4e-5f2c-11e7-90aa-74bd51f0ddb3.png)
![image](https://user-images.githubusercontent.com/23057153/27769153-56234428-5f2c-11e7-8722-57b66e30af72.png)

However, when I'm pressing your plugin's icon I get this screen
![image](https://user-images.githubusercontent.com/23057153/27769166-8449d862-5f2c-11e7-91ed-0e9754138e4b.png)

**Comment by yonzarecki** [comment]
Thank you! We're looking into it.

**Comment by yonzarecki** [comment]
OK, this error was because there aren't any result.
Now there is an error message, later will change this to a more stylized message (as this is not an error).
![ssdlbugquery cs technion ac il-stacks-325](https://user-images.githubusercontent.com/23148393/27769392-fff0ef7e-5f30-11e7-96b5-92cc85f2d571.png)
