### ISSUE TITLE
Initial results page design 

### ISSUE THREAD

**Issue by AdiOmari** [TechnionYP5777/Bugquery#32]
You did some very nice advancements in styling the site.
Did you consider using UI libraries like: [bootstrap ](http://getbootstrap.com/)or [semanticUI](http://semantic-ui.com/)? I reviewed the jsp pages and could not find references to either.

**Comment by yosefraisman** [comment]
@AdiOmari, I did consider Bootstrap, but here's why I currently don't think we really need it:
- Responsiveness isn't an issue for us as the site is meant primarily for desktops.
- Having our own CSS and HTML makes it easier to define our classes and styling options (and makes maintenance easier since it's code I wrote and am familiar with).
- It also makes the site more lightweight - no need to import javascript, for example, or styling options we don't use.

What do you think changing the implementation will improve?

**Comment by AdiOmari** [comment]
@yosefraisman the idea is that we can use their style for basic controls, and have our own custom design for the rest. It is not critical at this point, it is a suggestion that I think can make it easier for you.

**Comment by yossigil** [comment]
thought of reminding your of this

**Comment by AmitOhayon** [comment]
@yosefraisman @AdiOmari I think we passed on this?
