### ISSUE TITLE
Welcome Doron Meshulam

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Bugquery#67]

**Comment by mdoron** [comment]
@AdiOmari I read all your team meeting summaries and understand the general structure of the project. I was really enthusiastic about the idea of user voting since while reading I thought this is something that is missing from the project. 

Also, I read your wiki pages except the last part of the developers' guide which I will cover with one of the team mates, you can assign someone if you like or let me check with the guys when are they free.

**Comment by yosefraisman** [comment]
Welcome @mdoron! Enjoy your stay in the BugQuery wonderland!

![We're all mad here.](https://cloud.githubusercontent.com/assets/16455692/24425820/31744c44-140e-11e7-9487-dfa78f593be3.gif)

**Comment by yossigil** [comment]
Doron: if you do not show work in the first week it is considered vacation. Work is completing issues
