### ISSUE TITLE
Vacations

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#71]
**Notice**: you should announce vacation on the group's Telegram group / post a comment here. You may edit this comment.

| Member | Week1 | Week2 | Week3 | Week4 | Week5 | Week6 | Week7 | Week8 | Week9 | Week10 | Week11 | Week12 | Week13 |
|--------|-------|-------|-------|-------|-------|-------|-------|-------|-------|--------|--------|--------|--------|
|[Amit Ohayon](https://github.com/TechnionYP5777/Bugquery/issues/2)|       |       |       |       |       |       |       |       |:tada:|:tada:|        |        |        |
|[Doron Meshulam](https://github.com/TechnionYP5777/Bugquery/issues/69)|       |       |       |       |       |:tada:|       |       |       |:tada:|        |        |        |
|[Entony Lekhtman](https://github.com/TechnionYP5777/Bugquery/issues/6)|       |       |       |       |       |       |       |       |       |     :tada:    |        | :tada:   |        |
|[Roded Zats](https://github.com/TechnionYP5777/Bugquery/issues/10)|       |:tada:|       |       |       |       |       |       |       |   :tada:     |        |        |        |
|[Yonatan Zarecki](https://github.com/TechnionYP5777/Bugquery/issues/5)|       |:tada:|       |       |       |       |       |       |       |        |        |  :tada:  |        |
|[Yosef Raisman](https://github.com/TechnionYP5777/Bugquery/issues/4)|       |       |       |       |       |:tada:|       |       |       |        |        |    :tada:    |        |
|[Ziv Izhar](https://github.com/TechnionYP5777/Bugquery/issues/11)|        |       |       |       |       |       |       |       |       |        |  :tada:   |  :tada:   |        |

**Comment by yossigil** [comment]
I think the team was off on week1

**Comment by yossigil** [comment]
@AdiOmari : I asked @mdoron  to take care of the vacation issue. I don't think he did much.

**Comment by mdoron** [comment]
I opened this issue and anyone should fill this out since I'm new to this team and don't know what's going on here. I talked to some members and actually except Roded and Zarecki no one really knows if you put the whole team on vacation on the first and second week or not.

**Comment by yossigil** [comment]
Doron: this is your opportunity. Connect personally with each team member to introduce yourself and 
please mark the team off at week1

**Comment by yosefraisman** [comment]
Respectfully, we weren't off the first week; we did work independently and also as a team (as one can tell by the meeting minuets in our wiki).
Our so-called "vacation" was decided after 2 members arrived late to the course meeting. Apart from that, ours was one of the teams with the best attendance: 5 out of 6 members showed up - only Ziv couldn't make it, because of a family event.
The mild lateness of two team members (they got there within the first ten minutes) doesn't constitute a vacation in my opinion, definitely not a week-long vacation at that. (It also doesn't warrant the response of the lecturer, who marked us, on a whim, as missing four members - we were missing one).
Also- three team members were there on time, why exactly should they be punished?
Please reconsider @yossigil

**Comment by yossigil** [comment]
As usual, it is tough to fix the broken, then doing it right the first time...
Sorry.
