### ISSUE TITLE
Thinking group - Explore what PL we should use for parsing the web

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#98]
Check which programming-language is best for parsing the web when looking for traces in the web (as we discussed for the future). It can be python (strong contender), Java, C# whichever fits best.

**Comment by yonzarecki** [comment]
Looking into python html parsing libs. (I'll update my finding in this comment continuously)
From the standard library we have [HTMLParser](https://docs.python.org/2/library/htmlparser.html) which looks pretty convenient.
[BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) is also quite popular and I've heard of it before.

**Comment by tonylekhtman** [comment]
I have some experience in parsing using python, from other projects. 
I used lxml, xpath library. Pretty convenient.

**Comment by yonzarecki** [comment]
For Java I've used [htmlunit](http://htmlunit.sourceforge.net/) in the past, which is a GUI-less browser and is also capable of basic parsing of web-pages, this was sufficient at the time.

For more advanced html parsing after looking into these SO questions - [link](http://stackoverflow.com/questions/3152138/what-are-the-pros-and-cons-of-the-leading-java-html-parsers), [link](http://stackoverflow.com/questions/2835505/how-to-scan-a-website-or-page-for-info-and-bring-it-into-my-program), [link](http://stackoverflow.com/questions/2835505/how-to-scan-a-website-or-page-for-info-and-bring-it-into-my-program)

The most popular suggestion is [JSoup](https://jsoup.org/).
Another suggestion is [JTidy](http://jtidy.sourceforge.net/), which handles broken HTML but is less established than JSoup. 
In my opinion JSoup is the better choice, maybe combined with HTMLUnit that can handle the web page accesses.

**Comment by ZivIzhar** [comment]
What's the point in assigning me to that if you're already doing that? :/
Anyways, I went (in vain) over some parsing libraries.

Basically, our two main options are Java or Python.
In general, most of the people use JSoup (java).
There are many python web parsers, but the best is probably BeautifulSoup.

Since most of our project is in java, and there is no obvious advantage to python, I think we should stick to java.


Regarding HtmlUnit and JTidy - these are'nt meant for data extraction.
[link](http://stackoverflow.com/questions/3152138/what-are-the-pros-and-cons-of-the-leading-java-html-parsers/3154281#3154281)
 [link](http://stackoverflow.com/questions/12439078/jtidy-or-jsoup-for-java)

JSoup has a very easy to use API, and is super powerful for web parsing.
After going over several web parsing libraries, I think that JSoup is the best for us since it has everything we'll probably need.

**Comment by ZivIzhar** [comment]
There's this link with many html parsers names
[link](https://en.wikipedia.org/wiki/Comparison_of_HTML_parsers)

**Comment by yonzarecki** [comment]
Well I assigned both of us, to make us both go over the subject, and the fact that we got to the same conclusion makes it even stronger.
That's the strength of the thinking group in my opinion

**Comment by yonzarecki** [comment]
Quick look into C#, it doesn't seem to have an exceptionally strong parsing lib, and as our team prefers Java and python we won't use it probably.

So to summarize, if we want to incorporate the parsing core into all of our other code we can and should use Java. 
However, if we want a run-once solution python will probably be better because of the faster coding speed.
